package es.tributasenasturias.services.ws.imagenesmultas;

import javax.annotation.Resource;
import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.Holder;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.WebServiceException;

import es.tributasenasturias.services.ws.imagenesmultas.bd.Documentos;
import es.tributasenasturias.services.ws.imagenesmultas.utils.log.Logger;
import es.tributasenasturias.services.ws.imagenesmultas.utils.log.Preferencias.Preferencias;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */
@WebService(portName = "ImagenesSOAP", serviceName = "Imagenes", targetNamespace = "http://ImagenesMultas.ws.services.tributasenasturias.es/Imagenes/", wsdlLocation = "/wsdls/Imagenes.wsdl", endpointInterface = "es.tributasenasturias.services.ws.imagenesmultas.Imagenes")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain(file="HandlerChain.xml")
public class Imagenes_ImagenesSOAPImpl implements Imagenes {

	public Imagenes_ImagenesSOAPImpl() {
	}
	
	@Resource
	WebServiceContext context;
	/**
	 * 
	 * @param imagenes
	 * @param error
	 * @param boletin
	 * @param idFiscal
	 * @param anyo
	 */
	public void obtenerImagenes(String fechaInfraccion, String boletin, String idFiscal,
			Holder<ImagenesType> imagenes, Holder<String> error) {
		
		try {
			String idLlamada= (String) context.getMessageContext().get(Constantes.ID_LLAMADA);
			Preferencias pref= (Preferencias) context.getMessageContext().get(Constantes.PREFERENCIAS);
			if (pref==null) {
				throw new Exception ("No se han encontrado las preferencias en el contexto de la llamada");
			}
			Logger logger= new Logger(idLlamada, pref.getAppLogDir(), pref.getAppLogFile());
			logger.info("Petición obtener imágenes");
			logger.info("fechaInfraccion:" + fechaInfraccion);
			logger.info("boletin:" + boletin);
			logger.info("idFiscal:" + idFiscal);
			
			Documentos datos = new Documentos(pref, logger, idLlamada);
			datos.ObtenerImagenes(fechaInfraccion, boletin, idFiscal,
					imagenes, error);
	
			if(error.value!="")
				logger.error("ERROR:" + error.value);
			
			return;
		} catch (Exception e) {
			throw new WebServiceException(e);
		}
	}

}
