package es.tributasenasturias.services.ws.wsconsultadoindocumentos;

import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.Holder;

import es.tributasenasturias.services.ws.wsconsultadoindocumentos.utils.SalidaConsulta;
import es.tributasenasturias.services.ws.wsconsultadoindocumentos.utils.Log.GenericAppLogger;
import es.tributasenasturias.services.ws.wsconsultadoindocumentos.utils.Log.Logger;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 */
@WebService(portName = "WSConsultaDoinDocumentosSOAP", serviceName = "WSConsultaDoinDocumentos", targetNamespace = "http://WSConsultaDoinDocumentos.ws.services.tributasenasturias.es/WSConsultaDoinDocumentos/", wsdlLocation = "/wsdls/WSConsultaDoinDocumentos.wsdl", endpointInterface = "es.tributasenasturias.services.ws.wsconsultadoindocumentos.WSConsultaDoinDocumentos")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain (file= "./utils/Log/LogHandler/HandlerChain.xml")
public class WSConsultaDoinDocumentos_WSConsultaDoinDocumentosSOAPImpl implements WSConsultaDoinDocumentos {

	public WSConsultaDoinDocumentos_WSConsultaDoinDocumentosSOAPImpl() {}

	/**
	 * Consulta de documento en tabla DOIN_DOCUMENTOS_INTERNET
	 * @param nombre
	 * @param error
	 * @param tipo
	 * @param resultado
	 * @param documento
	 * @param descomprimir
	 */
	public void consultaDoinDocumento(String nombre, String tipo,
			boolean descomprimir, Holder<String> documento,
			Holder<String> error, Holder<String> resultado) {
		GenericAppLogger log=new Logger();
		try{
			log.trace("INICIO LLAMADA METODO WEB ConsultaDoinDocumentoInternet");

			OperacionesDoinDocumentosInternet consulta = new OperacionesDoinDocumentosInternet();
			SalidaConsulta resultadoConsulta = consulta.Ejecutar(nombre,tipo,descomprimir);
			documento.value=resultadoConsulta.getDocumento();
			error.value =resultadoConsulta.getError();
			resultado.value = resultadoConsulta.getResultado();

			log.trace("FIN LLAMADA METODO WEB ConsultaDoinDocumentoInternet");
		}catch (Exception ex){
			log.error("Error en la ejecución del servicio web ConsultaDoinDocumentoInternet: " + ex.getMessage());
			documento.value = "";
		}
	}

	/**
	 * Alta de documento en tabla DOIN_DOCUMENTOS_INTERNET
	 * @param nombre
	 * @param tipo
	 * @param codVerif
	 * @param nifSp
	 * @param nifPr
	 * @param xmlData
	 * @param tipoDoc
	 * @param idSesion
	 * @param comprimir
	 * @param documento
	 * @param error
	 * @param resultado
	 
	 
	 */
	public void altaDoinDocumento(String nombre, String tipo, String codVerif,
			String nifSp, String nifPr, String xmlData, String tipoDoc,String idSesion,
			boolean comprimir,Holder<String> documento, Holder<String> error,
			Holder<String> resultado) {
		GenericAppLogger log=new Logger();
		try{
			log.trace("INICIO LLAMADA METODO WEB altaDoinDocumentoInternet");

			OperacionesDoinDocumentosInternet operacionDoin = new OperacionesDoinDocumentosInternet();
			SalidaConsulta resultadoConsulta = operacionDoin.altaDocumento(nombre,tipo,codVerif, nifSp,nifPr, xmlData, tipoDoc,idSesion,comprimir);
			documento.value=resultadoConsulta.getDocumento();
			error.value =resultadoConsulta.getError();
			resultado.value = resultadoConsulta.getResultado();

			log.trace("FIN LLAMADA METODO WEB altaDoinDocumentoInternet");
		}catch (Exception ex){
			log.error("Error en la ejecución del servicio web altaDoinDocumento: " + ex.getMessage());
			documento.value="";
			error.value =ex.getMessage();
		}
	}

}
