
package es.tributasenasturias.seguridad.firma;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.3-06/19/2008 07:03 PM(bt)
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://localhost:7001")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -8500854763868391162L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private es.tributasenasturias.seguridad.firma.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception_Exception(String message, es.tributasenasturias.seguridad.firma.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception_Exception(String message, es.tributasenasturias.seguridad.firma.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.tributasenasturias.seguridad.firma.Exception
     */
    public es.tributasenasturias.seguridad.firma.Exception getFaultInfo() {
        return faultInfo;
    }

}
