
package es.tributasenasturias.seguridad.firma;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.spi.Provider;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.3-06/19/2008 07:03 PM(bt)
 * Generated source version: 2.1
 * 
 */
@SuppressWarnings("unchecked")
@WebServiceClient(name = "wsFirmaDigital", targetNamespace = "http://localhost:7001", wsdlLocation = "META-INF/wsdls/PXFirmaDigital.wsdl")
public class WsFirmaDigital
    extends Service
{

    private final static URL WSFIRMADIGITAL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.tributasenasturias.seguridad.firma.WsFirmaDigital.class.getName());

    static {
        URL url = null;
        try {
            Provider provider = Provider.provider();
            Class wlsProviderClass = null;
            Method wlsLocateWsdl = null;
            try {
                wlsProviderClass = Class.forName("weblogic.wsee.jaxws.spi.WLSProvider");
                wlsLocateWsdl = wlsProviderClass.getMethod("locateWsdl", Class.class);
            } catch (ClassNotFoundException cnfe) {
            } catch (NoSuchMethodException nsme) {
            }
            if ((wlsLocateWsdl!= null)&&wlsProviderClass.isAssignableFrom(provider.getClass())) {
                try {
                    url = ((URL) wlsLocateWsdl.invoke(provider, es.tributasenasturias.seguridad.firma.WsFirmaDigital.class));
                } catch (IllegalAccessException iae) {
                } catch (IllegalArgumentException ia) {
                } catch (InvocationTargetException ite) {
                }
            }
            if (url == null) {
                URL baseUrl;
                baseUrl = es.tributasenasturias.seguridad.firma.WsFirmaDigital.class.getResource(".");
                url = new URL(baseUrl, "wsdl/PXFirmaDigital.wsdl");
            }
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'META-INF/wsdls/PXFirmaDigital.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSFIRMADIGITAL_WSDL_LOCATION = url;
    }

    public WsFirmaDigital(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsFirmaDigital() {
        super(WSFIRMADIGITAL_WSDL_LOCATION, new QName("http://localhost:7001", "wsFirmaDigital"));
    }

    /**
     * 
     * @return
     *     returns FirmaDigital
     */
    @WebEndpoint(name = "servicesPort")
    public FirmaDigital getServicesPort() {
        return super.getPort(new QName("http://localhost:7001", "servicesPort"), FirmaDigital.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirmaDigital
     */
    @WebEndpoint(name = "servicesPort")
    public FirmaDigital getServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:7001", "servicesPort"), FirmaDigital.class, features);
    }

}
