<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://servicios.tributasenasturias.es/Asturcon/ConsultaDeuda/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AsturconConsultaDeuda" targetNamespace="http://servicios.tributasenasturias.es/Asturcon/ConsultaDeuda/">
  <wsdl:types>
    <xsd:schema
    	targetNamespace="http://servicios.tributasenasturias.es/Asturcon/ConsultaDeuda/">
    	<xsd:include schemaLocation="esquemaConsulta.xsd"></xsd:include>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="solicitarConsultaRequest">
    <wsdl:part element="tns:solicitarConsulta" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="solicitarConsultaResponse">
    <wsdl:part element="tns:solicitarConsultaResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="AsturconConsultaDeuda">
    <wsdl:operation name="solicitarConsulta">
      <wsdl:input message="tns:solicitarConsultaRequest"/>
      <wsdl:output message="tns:solicitarConsultaResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AsturconConsultaDeudaSOAP" type="tns:AsturconConsultaDeuda">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="solicitarConsulta">
      <soap:operation soapAction="http://servicios.tributasenasturias.es/Asturcon/ConsultaDeuda/solicitarConsulta"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AsturconConsultaDeuda">
    <wsdl:port binding="tns:AsturconConsultaDeudaSOAP" name="AsturconConsultaDeudaSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
