
package es.tributasenasturias.lanzador.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "lanzaPL", targetNamespace = "http://stpa/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LanzaPL {


    /**
     * 
     * @param nombre
     * @param nif
     * @param peticion
     * @param esquema
     * @param certificado
     * @param ip
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://stpa/services")
    @RequestWrapper(localName = "executePL", targetNamespace = "http://stpa/services", className = "es.tributasenasturias.lanzador.impl.ExecutePL")
    @ResponseWrapper(localName = "executePLResponse", targetNamespace = "http://stpa/services", className = "es.tributasenasturias.lanzador.impl.ExecutePLResponse")
    public String executePL(
        @WebParam(name = "esquema", targetNamespace = "http://stpa/services")
        String esquema,
        @WebParam(name = "peticion", targetNamespace = "http://stpa/services")
        String peticion,
        @WebParam(name = "IP", targetNamespace = "http://stpa/services")
        String ip,
        @WebParam(name = "NIF", targetNamespace = "http://stpa/services")
        String nif,
        @WebParam(name = "nombre", targetNamespace = "http://stpa/services")
        String nombre,
        @WebParam(name = "certificado", targetNamespace = "http://stpa/services")
        String certificado);

}
