package es.boe.subastas;

import javax.annotation.Resource;
import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.WebServiceException;

import es.boe.subastas.exceptions.SubastaException;
import es.boe.subastas.preferencias.Preferencias;
import es.tributasenasturias.utils.log.Logger;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */
@WebService(portName = "ServicioSubastasPort", serviceName = "ServicioSubastasBOE", targetNamespace = "http://www.boe.es/ServicioSubastas/", wsdlLocation = "/wsdls/GestionSubastas.wsdl", endpointInterface = "es.boe.subastas.ServicioSubastas")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain(file="HandlerChain.xml")
public class ServicioSubastasBOE_ServicioSubastasPortImpl implements
		ServicioSubastas {

	@Resource
	 WebServiceContext wsc;
	
	public ServicioSubastasBOE_ServicioSubastasPortImpl() {
	}

	/**
	 * 
	 * @param envio
	 * @return returns es.boe.subastas.RespuestaEnvio
	 */
	public RespuestaEnvio envioSubasta(String envio) {

		try{
			Preferencias pr= (Preferencias)wsc.getMessageContext().get(Constantes.PREFERENCIAS);
			Logger logger= (Logger) wsc.getMessageContext().get(Constantes.LOG);
			String idLlamada= (String) wsc.getMessageContext().get(Constantes.ID_LLAMADA);
			if (pr==null || logger==null || idLlamada==null) {
				throw new SubastaException("No se ha inicializado correctamente el servicio, faltan objetos necesarios(Preferencias, log o Identificador de llamada");
			}
			return SubastasImpl.newInstance(pr, logger, idLlamada).envioSubasta(envio);
		} catch (Exception e) {
			throw new WebServiceException("Error en "+this.getClass().getCanonicalName()+":"+e.getMessage(),e);
		}
	}

	/**
	 * 
	 * @param estado
	 * @return returns es.boe.subastas.RespuestaEstado
	 */
	public RespuestaEstado cambioEstadoSubasta(Estado estado) {
		try{
			Preferencias pr= (Preferencias)wsc.getMessageContext().get(Constantes.PREFERENCIAS);
			Logger logger= (Logger) wsc.getMessageContext().get(Constantes.LOG);
			String idLlamada= (String) wsc.getMessageContext().get(Constantes.ID_LLAMADA);
			if (pr==null || logger==null || idLlamada==null) {
				throw new SubastaException("No se ha inicializado correctamente el servicio, faltan objetos necesarios(Preferencias, log o Identificador de llamada");
			}
			return SubastasImpl.newInstance(pr, logger, idLlamada).cambioEstadoSubasta(estado);
		} catch (Exception e) {
			throw new WebServiceException("Error en "+this.getClass().getCanonicalName()+":"+e.getMessage(),e);
		}
	}

	/**
	 * 
	 * @param posturaFinal
	 * @return returns es.boe.subastas.RespuestaPosturaFinal
	 */
	public RespuestaPosturaFinal posturaFinal(PosturaFinal posturaFinal) {
		try{
			Preferencias pr= (Preferencias)wsc.getMessageContext().get(Constantes.PREFERENCIAS);
			Logger logger= (Logger) wsc.getMessageContext().get(Constantes.LOG);
			String idLlamada= (String) wsc.getMessageContext().get(Constantes.ID_LLAMADA);
			if (pr==null || logger==null || idLlamada==null) {
				throw new SubastaException("No se ha inicializado correctamente el servicio, faltan objetos necesarios(Preferencias, log o Identificador de llamada");
			}
			return SubastasImpl.newInstance(pr, logger, idLlamada).posturaFinal(posturaFinal);
		} catch (Exception e) {
			throw new WebServiceException("Error en "+this.getClass().getCanonicalName()+":"+e.getMessage(),e);
		}
	}

}
