
package es.tributasenasturias.servicios.calculo600generico;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for conceptoTypeEO.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="conceptoTypeEO">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TRANSMISIÓN DE ACCIONES, DERECHOS DE SUSCRIPCIÓN OBLIGACIONES Y TÍTULOS ANÁLOGOS"/>
 *     &lt;enumeration value="ANOTACIONES PREVENTIVAS"/>
 *     &lt;enumeration value="ARRENDAMIENTOS FINCAS RÚSTICAS"/>
 *     &lt;enumeration value="ARRENDAMIENTOS FINCAS URBANAS"/>
 *     &lt;enumeration value="ARRENDAMIENTO DE VIVIENDA HABITUAL"/>
 *     &lt;enumeration value="CONCESIONES ADMINISTRATIVAS Y OTROS CONCEPTOS"/>
 *     &lt;enumeration value="DOCUMENTOS NOTARIALES: DOCUMENTOS EN LOS QUE SE RENUNCIA A LA EXENCIÓN DEL IVA"/>
 *     &lt;enumeration value="DERECHOS REALES DE GARANTÍA"/>
 *     &lt;enumeration value="DOCUMENTOS NOTARIALES, OPERACIONES HIPOTECARIAS (PRÉSTAMOS, CANCELACIONES, SUBROGACIONES ...)"/>
 *     &lt;enumeration value="DOCUMENTOS NOTARIALES: SEGREGACIÓN"/>
 *     &lt;enumeration value="DOCUMENTOS NOTARIALES: AGRUPACIÓN"/>
 *     &lt;enumeration value="DOCUMENTOS NOTARIALES: DECLARACIÓN OBRA NUEVA"/>
 *     &lt;enumeration value="DOCUMENTOS NOTARIALES: DIVISIÓN HORIZONTAL"/>
 *     &lt;enumeration value="DOCUMENTOS NOTARIALES: ENTREGAS SUJETAS AL IVA"/>
 *     &lt;enumeration value="DOCUMENTOS NOTARIALES: OTROS DOCUMENTOS NOTARIALES"/>
 *     &lt;enumeration value="DOCUMENTOS NOTARIALES: VIVIENDAS PROTEGIDAS"/>
 *     &lt;enumeration value="EXPLOTACIONES AGRARIAS PRIORITARIAS"/>
 *     &lt;enumeration value="FIANZA"/>
 *     &lt;enumeration value="GRANDEZA SIN TÍTULOS: TRANSMISIÓN DIRECTA"/>
 *     &lt;enumeration value="GRANDEZA SIN TÍTULOS: TRANSMISIÓN TRANSVERSAL"/>
 *     &lt;enumeration value="GRANDEZA SIN TÍTULOS: REHABILITACIÓN Y RECONOCIMIENTO DE TÍTULOS EXTRANJEROS"/>
 *     &lt;enumeration value="DOCUMENTOS NO SUJETOS"/>
 *     &lt;enumeration value="PENSIONES"/>
 *     &lt;enumeration value="PRÉSTAMOS Y OBLIGACIONES"/>
 *     &lt;enumeration value="SOCIEDADES NO ANÓNIMAS: CONSTITUCIÓN"/>
 *     &lt;enumeration value="SOCIEDADES NO ANÓNIMAS: AMPLIACIÓN DE CAPITAL"/>
 *     &lt;enumeration value="SOCIEDADES NO ANÓNIMAS: DISMINUCIÓN DE CAPITAL"/>
 *     &lt;enumeration value="SOCIEDADES NO ANÓNIMAS: DISOLUCIÓN Y/O LIQUIDACIÓN"/>
 *     &lt;enumeration value="SOCIEDADES NO ANÓNIMAS: DISOLUCIÓN SIN LIQUIDACIÓN"/>
 *     &lt;enumeration value="SOCIEDADES NO ANÓNIMAS: FUSIÓN"/>
 *     &lt;enumeration value="SOCIEDADES NO ANÓNIMAS: ESCISIÓN"/>
 *     &lt;enumeration value="SOCIEDADES NO ANÓNIMAS: APORTACIONES DE SOCIOS POR PÉRDIDAS SOCIALES"/>
 *     &lt;enumeration value="SOCIEDADES NO ANÓNIMAS: TRASLADO A ESPAÑA DE SEDE O DOMICILIO SOCIAL"/>
 *     &lt;enumeration value="SOCIEDADES NO ANÓNIMAS: LIQUIDACIÓN DE SOCIEDAD"/>
 *     &lt;enumeration value="SOCIEDADES ANÓNIMAS: CONSTITUCIÓN"/>
 *     &lt;enumeration value="SOCIEDADES ANÓNIMAS: AMPLIACIÓN DE CAPITAL"/>
 *     &lt;enumeration value="SOCIEDADES ANÓNIMAS: DISMINUCIÓN DE CAPITAL"/>
 *     &lt;enumeration value="SOCIEDADES ANÓNIMAS: DISOLUCIÓN Y/O LIQUIDACIÓN"/>
 *     &lt;enumeration value="SOCIEDADES ANÓNIMAS: DISOLUCIÓN SIN LIQUIDACIÓN"/>
 *     &lt;enumeration value="SOCIEDADES ANÓNIMAS: FUSIÓN"/>
 *     &lt;enumeration value="SOCIEDADES ANÓNIMAS: ESCISIÓN"/>
 *     &lt;enumeration value="SOCIEDADES ANÓNIMAS: APORTACIONES DE SOCIOS POR PÉRDIDAS SOCIALES"/>
 *     &lt;enumeration value="SOCIEDADES ANÓNIMAS: TRASLADO A ESPAÑA DE SEDE O DOMICILIO SOCIAL"/>
 *     &lt;enumeration value="SOCIEDADES ANÓNIMAS: DISOLUCIÓN SIN LIQUIDACIÓN"/>
 *     &lt;enumeration value="TRANSMISIÓN DE ACCIONES, PARTICIPACIONES SOCIALES, DERECHOS DE SUSCRIPCIÓN Y OTROS VALORES MOBILIARIOS"/>
 *     &lt;enumeration value="TÍTULOS CON GRANDEZA: TRANSMISIÓN DIRECTA"/>
 *     &lt;enumeration value="TÍTULOS CON GRANDEZA: TRANSMISIÓN TRANSVERSAL"/>
 *     &lt;enumeration value="TÍTULOS CON GRANDEZA: REHABILITACIÓN Y RECONOCIMIENTO DE TÍTULOS EXTRANJEROS"/>
 *     &lt;enumeration value="TRANSMISIÓN DE INMUEBLES CON NEGOCIO"/>
 *     &lt;enumeration value="TRANS. Y DRCHOS REALES SOBRE MUEBLES Y PARTICIPACIONES SOBRE C.B. EXCEPTO AUTO. Y VAL. MOBILIARIOS"/>
 *     &lt;enumeration value="TRANSMISIÓN DE VIVIENDAS CALIFICADAS COMO PROTEGIDAS"/>
 *     &lt;enumeration value="TRANSMISIÓN Y DERECHOS REALES SOBRE INMUEBLES RÚSTICOS"/>
 *     &lt;enumeration value="TRANSMISIÓN CON DERECHO A RENUNCIAR A LA EXENCIÓN DE IVA, SIN EFECTUAR DICHA RENUNCIA"/>
 *     &lt;enumeration value="TÍTULOS SIN GRANDEZA: TRANSMISIÓN DIRECTA"/>
 *     &lt;enumeration value="TÍTULOS SIN GRANDEZA: TRANSMISIÓN TRANSVERSAL"/>
 *     &lt;enumeration value="TÍTULOS SIN GRANDEZA: REHABILITACIÓN Y RECONOCIMIENTO DE TÍTULOS EXTRANJEROS"/>
 *     &lt;enumeration value="TRANSMISIÓN Y DERECHOS REALES SOBRE INMUEBLES URBANOS: SOLARES"/>
 *     &lt;enumeration value="TRANSMISIÓN Y DERECHOS REALES SOBRE INMUEBLES URBANOS: VIVIENDAS"/>
 *     &lt;enumeration value="TRANSMISIÓN Y DERECHOS REALES SOBRE INMUEBLES URBANOS: LOCALES Y OTRAS EDIFICACIONES"/>
 *     &lt;enumeration value="TRANSMISIÓN DE VALORES Y DERECHOS DE SUSCRIPCIÓN Y DE LAS LETRAS DEL TESORO PARA NO RESIDENTES"/>
 *     &lt;enumeration value="NOVACIÓN COVID-19 VH"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "conceptoTypeEO")
@XmlEnum
public enum ConceptoTypeEO {

    @XmlEnumValue("TRANSMISI\u00d3N DE ACCIONES, DERECHOS DE SUSCRIPCI\u00d3N OBLIGACIONES Y T\u00cdTULOS AN\u00c1LOGOS")
    TRANSMISIÓN_DE_ACCIONES_DERECHOS_DE_SUSCRIPCIÓN_OBLIGACIONES_Y_TÍTULOS_ANÁLOGOS("TRANSMISI\u00d3N DE ACCIONES, DERECHOS DE SUSCRIPCI\u00d3N OBLIGACIONES Y T\u00cdTULOS AN\u00c1LOGOS"),
    @XmlEnumValue("ANOTACIONES PREVENTIVAS")
    ANOTACIONES_PREVENTIVAS("ANOTACIONES PREVENTIVAS"),
    @XmlEnumValue("ARRENDAMIENTOS FINCAS R\u00daSTICAS")
    ARRENDAMIENTOS_FINCAS_RÚSTICAS("ARRENDAMIENTOS FINCAS R\u00daSTICAS"),
    @XmlEnumValue("ARRENDAMIENTOS FINCAS URBANAS")
    ARRENDAMIENTOS_FINCAS_URBANAS("ARRENDAMIENTOS FINCAS URBANAS"),
    @XmlEnumValue("ARRENDAMIENTO DE VIVIENDA HABITUAL")
    ARRENDAMIENTO_DE_VIVIENDA_HABITUAL("ARRENDAMIENTO DE VIVIENDA HABITUAL"),
    @XmlEnumValue("CONCESIONES ADMINISTRATIVAS Y OTROS CONCEPTOS")
    CONCESIONES_ADMINISTRATIVAS_Y_OTROS_CONCEPTOS("CONCESIONES ADMINISTRATIVAS Y OTROS CONCEPTOS"),
    @XmlEnumValue("DOCUMENTOS NOTARIALES: DOCUMENTOS EN LOS QUE SE RENUNCIA A LA EXENCI\u00d3N DEL IVA")
    DOCUMENTOS_NOTARIALES_DOCUMENTOS_EN_LOS_QUE_SE_RENUNCIA_A_LA_EXENCIÓN_DEL_IVA("DOCUMENTOS NOTARIALES: DOCUMENTOS EN LOS QUE SE RENUNCIA A LA EXENCI\u00d3N DEL IVA"),
    @XmlEnumValue("DERECHOS REALES DE GARANT\u00cdA")
    DERECHOS_REALES_DE_GARANTÍA("DERECHOS REALES DE GARANT\u00cdA"),
    @XmlEnumValue("DOCUMENTOS NOTARIALES, OPERACIONES HIPOTECARIAS (PR\u00c9STAMOS, CANCELACIONES, SUBROGACIONES ...)")
    DOCUMENTOS_NOTARIALES_OPERACIONES_HIPOTECARIAS_PRÉSTAMOS_CANCELACIONES_SUBROGACIONES("DOCUMENTOS NOTARIALES, OPERACIONES HIPOTECARIAS (PR\u00c9STAMOS, CANCELACIONES, SUBROGACIONES ...)"),
    @XmlEnumValue("DOCUMENTOS NOTARIALES: SEGREGACI\u00d3N")
    DOCUMENTOS_NOTARIALES_SEGREGACIÓN("DOCUMENTOS NOTARIALES: SEGREGACI\u00d3N"),
    @XmlEnumValue("DOCUMENTOS NOTARIALES: AGRUPACI\u00d3N")
    DOCUMENTOS_NOTARIALES_AGRUPACIÓN("DOCUMENTOS NOTARIALES: AGRUPACI\u00d3N"),
    @XmlEnumValue("DOCUMENTOS NOTARIALES: DECLARACI\u00d3N OBRA NUEVA")
    DOCUMENTOS_NOTARIALES_DECLARACIÓN_OBRA_NUEVA("DOCUMENTOS NOTARIALES: DECLARACI\u00d3N OBRA NUEVA"),
    @XmlEnumValue("DOCUMENTOS NOTARIALES: DIVISI\u00d3N HORIZONTAL")
    DOCUMENTOS_NOTARIALES_DIVISIÓN_HORIZONTAL("DOCUMENTOS NOTARIALES: DIVISI\u00d3N HORIZONTAL"),
    @XmlEnumValue("DOCUMENTOS NOTARIALES: ENTREGAS SUJETAS AL IVA")
    DOCUMENTOS_NOTARIALES_ENTREGAS_SUJETAS_AL_IVA("DOCUMENTOS NOTARIALES: ENTREGAS SUJETAS AL IVA"),
    @XmlEnumValue("DOCUMENTOS NOTARIALES: OTROS DOCUMENTOS NOTARIALES")
    DOCUMENTOS_NOTARIALES_OTROS_DOCUMENTOS_NOTARIALES("DOCUMENTOS NOTARIALES: OTROS DOCUMENTOS NOTARIALES"),
    @XmlEnumValue("DOCUMENTOS NOTARIALES: VIVIENDAS PROTEGIDAS")
    DOCUMENTOS_NOTARIALES_VIVIENDAS_PROTEGIDAS("DOCUMENTOS NOTARIALES: VIVIENDAS PROTEGIDAS"),
    @XmlEnumValue("EXPLOTACIONES AGRARIAS PRIORITARIAS")
    EXPLOTACIONES_AGRARIAS_PRIORITARIAS("EXPLOTACIONES AGRARIAS PRIORITARIAS"),
    FIANZA("FIANZA"),
    @XmlEnumValue("GRANDEZA SIN T\u00cdTULOS: TRANSMISI\u00d3N DIRECTA")
    GRANDEZA_SIN_TÍTULOS_TRANSMISIÓN_DIRECTA("GRANDEZA SIN T\u00cdTULOS: TRANSMISI\u00d3N DIRECTA"),
    @XmlEnumValue("GRANDEZA SIN T\u00cdTULOS: TRANSMISI\u00d3N TRANSVERSAL")
    GRANDEZA_SIN_TÍTULOS_TRANSMISIÓN_TRANSVERSAL("GRANDEZA SIN T\u00cdTULOS: TRANSMISI\u00d3N TRANSVERSAL"),
    @XmlEnumValue("GRANDEZA SIN T\u00cdTULOS: REHABILITACI\u00d3N Y RECONOCIMIENTO DE T\u00cdTULOS EXTRANJEROS")
    GRANDEZA_SIN_TÍTULOS_REHABILITACIÓN_Y_RECONOCIMIENTO_DE_TÍTULOS_EXTRANJEROS("GRANDEZA SIN T\u00cdTULOS: REHABILITACI\u00d3N Y RECONOCIMIENTO DE T\u00cdTULOS EXTRANJEROS"),
    @XmlEnumValue("DOCUMENTOS NO SUJETOS")
    DOCUMENTOS_NO_SUJETOS("DOCUMENTOS NO SUJETOS"),
    PENSIONES("PENSIONES"),
    @XmlEnumValue("PR\u00c9STAMOS Y OBLIGACIONES")
    PRÉSTAMOS_Y_OBLIGACIONES("PR\u00c9STAMOS Y OBLIGACIONES"),
    @XmlEnumValue("SOCIEDADES NO AN\u00d3NIMAS: CONSTITUCI\u00d3N")
    SOCIEDADES_NO_ANÓNIMAS_CONSTITUCIÓN("SOCIEDADES NO AN\u00d3NIMAS: CONSTITUCI\u00d3N"),
    @XmlEnumValue("SOCIEDADES NO AN\u00d3NIMAS: AMPLIACI\u00d3N DE CAPITAL")
    SOCIEDADES_NO_ANÓNIMAS_AMPLIACIÓN_DE_CAPITAL("SOCIEDADES NO AN\u00d3NIMAS: AMPLIACI\u00d3N DE CAPITAL"),
    @XmlEnumValue("SOCIEDADES NO AN\u00d3NIMAS: DISMINUCI\u00d3N DE CAPITAL")
    SOCIEDADES_NO_ANÓNIMAS_DISMINUCIÓN_DE_CAPITAL("SOCIEDADES NO AN\u00d3NIMAS: DISMINUCI\u00d3N DE CAPITAL"),
    @XmlEnumValue("SOCIEDADES NO AN\u00d3NIMAS: DISOLUCI\u00d3N Y/O LIQUIDACI\u00d3N")
    SOCIEDADES_NO_ANÓNIMAS_DISOLUCIÓN_Y_O_LIQUIDACIÓN("SOCIEDADES NO AN\u00d3NIMAS: DISOLUCI\u00d3N Y/O LIQUIDACI\u00d3N"),
    @XmlEnumValue("SOCIEDADES NO AN\u00d3NIMAS: DISOLUCI\u00d3N SIN LIQUIDACI\u00d3N")
    SOCIEDADES_NO_ANÓNIMAS_DISOLUCIÓN_SIN_LIQUIDACIÓN("SOCIEDADES NO AN\u00d3NIMAS: DISOLUCI\u00d3N SIN LIQUIDACI\u00d3N"),
    @XmlEnumValue("SOCIEDADES NO AN\u00d3NIMAS: FUSI\u00d3N")
    SOCIEDADES_NO_ANÓNIMAS_FUSIÓN("SOCIEDADES NO AN\u00d3NIMAS: FUSI\u00d3N"),
    @XmlEnumValue("SOCIEDADES NO AN\u00d3NIMAS: ESCISI\u00d3N")
    SOCIEDADES_NO_ANÓNIMAS_ESCISIÓN("SOCIEDADES NO AN\u00d3NIMAS: ESCISI\u00d3N"),
    @XmlEnumValue("SOCIEDADES NO AN\u00d3NIMAS: APORTACIONES DE SOCIOS POR P\u00c9RDIDAS SOCIALES")
    SOCIEDADES_NO_ANÓNIMAS_APORTACIONES_DE_SOCIOS_POR_PÉRDIDAS_SOCIALES("SOCIEDADES NO AN\u00d3NIMAS: APORTACIONES DE SOCIOS POR P\u00c9RDIDAS SOCIALES"),
    @XmlEnumValue("SOCIEDADES NO AN\u00d3NIMAS: TRASLADO A ESPA\u00d1A DE SEDE O DOMICILIO SOCIAL")
    SOCIEDADES_NO_ANÓNIMAS_TRASLADO_A_ESPAÑA_DE_SEDE_O_DOMICILIO_SOCIAL("SOCIEDADES NO AN\u00d3NIMAS: TRASLADO A ESPA\u00d1A DE SEDE O DOMICILIO SOCIAL"),
    @XmlEnumValue("SOCIEDADES NO AN\u00d3NIMAS: LIQUIDACI\u00d3N DE SOCIEDAD")
    SOCIEDADES_NO_ANÓNIMAS_LIQUIDACIÓN_DE_SOCIEDAD("SOCIEDADES NO AN\u00d3NIMAS: LIQUIDACI\u00d3N DE SOCIEDAD"),
    @XmlEnumValue("SOCIEDADES AN\u00d3NIMAS: CONSTITUCI\u00d3N")
    SOCIEDADES_ANÓNIMAS_CONSTITUCIÓN("SOCIEDADES AN\u00d3NIMAS: CONSTITUCI\u00d3N"),
    @XmlEnumValue("SOCIEDADES AN\u00d3NIMAS: AMPLIACI\u00d3N DE CAPITAL")
    SOCIEDADES_ANÓNIMAS_AMPLIACIÓN_DE_CAPITAL("SOCIEDADES AN\u00d3NIMAS: AMPLIACI\u00d3N DE CAPITAL"),
    @XmlEnumValue("SOCIEDADES AN\u00d3NIMAS: DISMINUCI\u00d3N DE CAPITAL")
    SOCIEDADES_ANÓNIMAS_DISMINUCIÓN_DE_CAPITAL("SOCIEDADES AN\u00d3NIMAS: DISMINUCI\u00d3N DE CAPITAL"),
    @XmlEnumValue("SOCIEDADES AN\u00d3NIMAS: DISOLUCI\u00d3N Y/O LIQUIDACI\u00d3N")
    SOCIEDADES_ANÓNIMAS_DISOLUCIÓN_Y_O_LIQUIDACIÓN("SOCIEDADES AN\u00d3NIMAS: DISOLUCI\u00d3N Y/O LIQUIDACI\u00d3N"),
    @XmlEnumValue("SOCIEDADES AN\u00d3NIMAS: DISOLUCI\u00d3N SIN LIQUIDACI\u00d3N")
    SOCIEDADES_ANÓNIMAS_DISOLUCIÓN_SIN_LIQUIDACIÓN("SOCIEDADES AN\u00d3NIMAS: DISOLUCI\u00d3N SIN LIQUIDACI\u00d3N"),
    @XmlEnumValue("SOCIEDADES AN\u00d3NIMAS: FUSI\u00d3N")
    SOCIEDADES_ANÓNIMAS_FUSIÓN("SOCIEDADES AN\u00d3NIMAS: FUSI\u00d3N"),
    @XmlEnumValue("SOCIEDADES AN\u00d3NIMAS: ESCISI\u00d3N")
    SOCIEDADES_ANÓNIMAS_ESCISIÓN("SOCIEDADES AN\u00d3NIMAS: ESCISI\u00d3N"),
    @XmlEnumValue("SOCIEDADES AN\u00d3NIMAS: APORTACIONES DE SOCIOS POR P\u00c9RDIDAS SOCIALES")
    SOCIEDADES_ANÓNIMAS_APORTACIONES_DE_SOCIOS_POR_PÉRDIDAS_SOCIALES("SOCIEDADES AN\u00d3NIMAS: APORTACIONES DE SOCIOS POR P\u00c9RDIDAS SOCIALES"),
    @XmlEnumValue("SOCIEDADES AN\u00d3NIMAS: TRASLADO A ESPA\u00d1A DE SEDE O DOMICILIO SOCIAL")
    SOCIEDADES_ANÓNIMAS_TRASLADO_A_ESPAÑA_DE_SEDE_O_DOMICILIO_SOCIAL("SOCIEDADES AN\u00d3NIMAS: TRASLADO A ESPA\u00d1A DE SEDE O DOMICILIO SOCIAL"),
    @XmlEnumValue("TRANSMISI\u00d3N DE ACCIONES, PARTICIPACIONES SOCIALES, DERECHOS DE SUSCRIPCI\u00d3N Y OTROS VALORES MOBILIARIOS")
    TRANSMISIÓN_DE_ACCIONES_PARTICIPACIONES_SOCIALES_DERECHOS_DE_SUSCRIPCIÓN_Y_OTROS_VALORES_MOBILIARIOS("TRANSMISI\u00d3N DE ACCIONES, PARTICIPACIONES SOCIALES, DERECHOS DE SUSCRIPCI\u00d3N Y OTROS VALORES MOBILIARIOS"),
    @XmlEnumValue("T\u00cdTULOS CON GRANDEZA: TRANSMISI\u00d3N DIRECTA")
    TÍTULOS_CON_GRANDEZA_TRANSMISIÓN_DIRECTA("T\u00cdTULOS CON GRANDEZA: TRANSMISI\u00d3N DIRECTA"),
    @XmlEnumValue("T\u00cdTULOS CON GRANDEZA: TRANSMISI\u00d3N TRANSVERSAL")
    TÍTULOS_CON_GRANDEZA_TRANSMISIÓN_TRANSVERSAL("T\u00cdTULOS CON GRANDEZA: TRANSMISI\u00d3N TRANSVERSAL"),
    @XmlEnumValue("T\u00cdTULOS CON GRANDEZA: REHABILITACI\u00d3N Y RECONOCIMIENTO DE T\u00cdTULOS EXTRANJEROS")
    TÍTULOS_CON_GRANDEZA_REHABILITACIÓN_Y_RECONOCIMIENTO_DE_TÍTULOS_EXTRANJEROS("T\u00cdTULOS CON GRANDEZA: REHABILITACI\u00d3N Y RECONOCIMIENTO DE T\u00cdTULOS EXTRANJEROS"),
    @XmlEnumValue("TRANSMISI\u00d3N DE INMUEBLES CON NEGOCIO")
    TRANSMISIÓN_DE_INMUEBLES_CON_NEGOCIO("TRANSMISI\u00d3N DE INMUEBLES CON NEGOCIO"),
    @XmlEnumValue("TRANS. Y DRCHOS REALES SOBRE MUEBLES Y PARTICIPACIONES SOBRE C.B. EXCEPTO AUTO. Y VAL. MOBILIARIOS")
    TRANS_Y_DRCHOS_REALES_SOBRE_MUEBLES_Y_PARTICIPACIONES_SOBRE_C_B_EXCEPTO_AUTO_Y_VAL_MOBILIARIOS("TRANS. Y DRCHOS REALES SOBRE MUEBLES Y PARTICIPACIONES SOBRE C.B. EXCEPTO AUTO. Y VAL. MOBILIARIOS"),
    @XmlEnumValue("TRANSMISI\u00d3N DE VIVIENDAS CALIFICADAS COMO PROTEGIDAS")
    TRANSMISIÓN_DE_VIVIENDAS_CALIFICADAS_COMO_PROTEGIDAS("TRANSMISI\u00d3N DE VIVIENDAS CALIFICADAS COMO PROTEGIDAS"),
    @XmlEnumValue("TRANSMISI\u00d3N Y DERECHOS REALES SOBRE INMUEBLES R\u00daSTICOS")
    TRANSMISIÓN_Y_DERECHOS_REALES_SOBRE_INMUEBLES_RÚSTICOS("TRANSMISI\u00d3N Y DERECHOS REALES SOBRE INMUEBLES R\u00daSTICOS"),
    @XmlEnumValue("TRANSMISI\u00d3N CON DERECHO A RENUNCIAR A LA EXENCI\u00d3N DE IVA, SIN EFECTUAR DICHA RENUNCIA")
    TRANSMISIÓN_CON_DERECHO_A_RENUNCIAR_A_LA_EXENCIÓN_DE_IVA_SIN_EFECTUAR_DICHA_RENUNCIA("TRANSMISI\u00d3N CON DERECHO A RENUNCIAR A LA EXENCI\u00d3N DE IVA, SIN EFECTUAR DICHA RENUNCIA"),
    @XmlEnumValue("T\u00cdTULOS SIN GRANDEZA: TRANSMISI\u00d3N DIRECTA")
    TÍTULOS_SIN_GRANDEZA_TRANSMISIÓN_DIRECTA("T\u00cdTULOS SIN GRANDEZA: TRANSMISI\u00d3N DIRECTA"),
    @XmlEnumValue("T\u00cdTULOS SIN GRANDEZA: TRANSMISI\u00d3N TRANSVERSAL")
    TÍTULOS_SIN_GRANDEZA_TRANSMISIÓN_TRANSVERSAL("T\u00cdTULOS SIN GRANDEZA: TRANSMISI\u00d3N TRANSVERSAL"),
    @XmlEnumValue("T\u00cdTULOS SIN GRANDEZA: REHABILITACI\u00d3N Y RECONOCIMIENTO DE T\u00cdTULOS EXTRANJEROS")
    TÍTULOS_SIN_GRANDEZA_REHABILITACIÓN_Y_RECONOCIMIENTO_DE_TÍTULOS_EXTRANJEROS("T\u00cdTULOS SIN GRANDEZA: REHABILITACI\u00d3N Y RECONOCIMIENTO DE T\u00cdTULOS EXTRANJEROS"),
    @XmlEnumValue("TRANSMISI\u00d3N Y DERECHOS REALES SOBRE INMUEBLES URBANOS: SOLARES")
    TRANSMISIÓN_Y_DERECHOS_REALES_SOBRE_INMUEBLES_URBANOS_SOLARES("TRANSMISI\u00d3N Y DERECHOS REALES SOBRE INMUEBLES URBANOS: SOLARES"),
    @XmlEnumValue("TRANSMISI\u00d3N Y DERECHOS REALES SOBRE INMUEBLES URBANOS: VIVIENDAS")
    TRANSMISIÓN_Y_DERECHOS_REALES_SOBRE_INMUEBLES_URBANOS_VIVIENDAS("TRANSMISI\u00d3N Y DERECHOS REALES SOBRE INMUEBLES URBANOS: VIVIENDAS"),
    @XmlEnumValue("TRANSMISI\u00d3N Y DERECHOS REALES SOBRE INMUEBLES URBANOS: LOCALES Y OTRAS EDIFICACIONES")
    TRANSMISIÓN_Y_DERECHOS_REALES_SOBRE_INMUEBLES_URBANOS_LOCALES_Y_OTRAS_EDIFICACIONES("TRANSMISI\u00d3N Y DERECHOS REALES SOBRE INMUEBLES URBANOS: LOCALES Y OTRAS EDIFICACIONES"),
    @XmlEnumValue("TRANSMISI\u00d3N DE VALORES Y DERECHOS DE SUSCRIPCI\u00d3N Y DE LAS LETRAS DEL TESORO PARA NO RESIDENTES")
    TRANSMISIÓN_DE_VALORES_Y_DERECHOS_DE_SUSCRIPCIÓN_Y_DE_LAS_LETRAS_DEL_TESORO_PARA_NO_RESIDENTES("TRANSMISI\u00d3N DE VALORES Y DERECHOS DE SUSCRIPCI\u00d3N Y DE LAS LETRAS DEL TESORO PARA NO RESIDENTES"),
    @XmlEnumValue("NOVACI\u00d3N COVID-19 VH")
    NOVACIÓN_COVID_19_VH("NOVACI\u00d3N COVID-19 VH");
    private final String value;

    ConceptoTypeEO(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConceptoTypeEO fromValue(String v) {
        for (ConceptoTypeEO c: ConceptoTypeEO.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
