package es.stpa.itp_dgt;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.Holder;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.WebServiceException;

import es.stpa.itp_dgt.preferencias.Preferencias;
import es.stpa.itp_dgt.utils.Constantes;
import es.stpa.itp_dgt.utils.Utils;
import es.trafico.servicios.vehiculos.accesosexternos.webservices.InfoErrorDTO;
import es.trafico.servicios.vehiculos.accesosexternos.webservices.ResultadoDTO;
import es.tributasenasturias.utils.log.Logger;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */
@WebService(portName = "itp_dgtSOAP", serviceName = "itp_dgt", targetNamespace = "http://itp_dgt.stpa.es", wsdlLocation = "/wsdls/itp_dgt.wsdl", endpointInterface = "es.stpa.itp_dgt.ItpDgt")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain (file="HandlerChain.xml")
public class itp_dgt_itp_dgtSOAPImpl implements ItpDgt {
	@Resource WebServiceContext wcontext;
	public itp_dgt_itp_dgtSOAPImpl() {
	}

	/**
	 * 
	 * @param referenciaRele
	 * @param estado
	 * @param fichero
	 * @param errores
	 */
	public void enviarFichero(Holder<String> fichero,
			Holder<String> referenciaRele, Holder<String> estado,
			Holder<ErroresType> errores) {
		
		Preferencias pref= (Preferencias) wcontext.getMessageContext().get(Constantes.PREFERENCIAS);
		
				
		Logger log=(Logger) wcontext.getMessageContext().get(Constantes.LOG);
		
		try{
			if (pref==null)
			{			
				pref = new Preferencias();
			}
			String idLlamada = (String) wcontext.getMessageContext().get(Constantes.IDSESION);
			if (idLlamada == null)
			{
				idLlamada = Utils.getIdLlamada();
			}
			
			
			
			DGTClient cliente=new DGTClient(pref, log, idLlamada);
			ResultadoDTO resDTO = cliente.enviarFichero(fichero.value);
			referenciaRele.value=resDTO.getReferencia();
			estado.value=resDTO.getEstado();
			
			fichero.value=resDTO.getFichero();
			
			ErroresType listaErrores;
			if (resDTO.getInfoErrores().size()>0)
			{
				listaErrores=new ErroresType();
				List<ErrorType> l=listaErrores.getError();
				for(InfoErrorDTO i:resDTO.getInfoErrores()){
					ErrorType e=new ErrorType();
					e.setCodigo(i.getCodigoError());
					e.setDescripcion(i.getDescripcionError());
					l.add(e);
				}
				errores.value=listaErrores;
			}
			
		}
		catch(Exception ex){
			log.error(ex.getMessage());
			throw new WebServiceException("Error envio de fichero");
		}
		
		
		
		
		return;
	}

}
