package es.tributasenasturias.apremios;

import javax.annotation.Resource;
import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.Holder;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.WebServiceException;

import es.tributasenasturias.apremios.preferencias.Preferencias;
import es.tributasenasturias.apremios.proxy.ResultadoEnvioPdf;
import es.tributasenasturias.apremios.util.Constantes;
import es.tributasenasturias.log.ILog;
import es.tributasenasturias.log.TributasLogger;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */
@WebService(portName = "ApremioPdfSOAP", serviceName = "GestionPdfApremio", targetNamespace = "http://apremios.tributasenasturias.es/GestionPdfApremio", wsdlLocation = "/wsdls/ApremioPdf.wsdl", endpointInterface = "es.tributasenasturias.apremios.GestionPdfApremio")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain(file="HandlerChain.xml")
public class GestionPdfApremio_ApremioPdfSOAPImpl implements GestionPdfApremio {

	@Resource
	WebServiceContext ctx;
	public GestionPdfApremio_ApremioPdfSOAPImpl() {
	}

	/**
	 * 
	 * @param codigoResultado
	 * @param claveLiquidacion
	 * @param nifDeudor
	 * @param resultadoAEAT
	 * @param esError
	 * @param idEperValor
	 * @param codigoUsuario
	 */
	public void envioPdf(String claveLiquidacion, String nifDeudor,
			int idEperValor, String codigoUsuario, Holder<Boolean> esError,
			Holder<String> codigoResultado,
			Holder<ResultadoAEATType> resultadoAEAT) {
		esError.value= new Boolean(false);
		ILog logger=null;
		try {
			Preferencias pref = (Preferencias)ctx.getMessageContext().get(Constantes.PREFERENCIAS);
			String idLlamada= (String)ctx.getMessageContext().get(Constantes.IDSESION);
			logger= new TributasLogger(pref.getModoLog(),pref.getFicheroLogAplicacion(), idLlamada);
			logger.info("Inicio de servicio de envío de pdf de apremio a la AEAT");
			ApremioPdfImpl apremio= new ApremioPdfImpl(pref,idLlamada, logger);
			ResultadoEnvioPdf resultado= apremio.enviarPdf(claveLiquidacion, nifDeudor, idEperValor,codigoUsuario);
			esError.value= resultado.esError();
			codigoResultado.value= resultado.getCodError();
			resultadoAEAT.value= resultado.getResultadoAEAT();
		} 
		catch (Exception e){
			if (logger!=null) {
				logger.error("Error inesperado en el envío de PDF a la AEAT:"+e.getMessage(),e);
			} else {
				System.err.println("Error inesperado en el envío de PDF a la AEAT:"+e.getMessage());
			}
			throw new WebServiceException("Error inesperado en el envío de PDF a la AEAT:  " + e.getMessage(),e);
		} finally {
			if (logger!=null) {
				logger.info("Fin de servicio de envío de pdf de apremio a la AEAT");
			}
		}
		return;
	}
}
