package es.tributasenasturias.services.ws.custodiaimagenes;

import javax.annotation.Resource;
import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.Holder;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.WebServiceException;

import es.tributasenasturias.services.ws.custodiaimagenes.bd.Datos;
import es.tributasenasturias.services.ws.custodiaimagenes.utils.Preferencias.Preferencias;
import es.tributasenasturias.services.ws.custodiaimagenes.utils.log.Logger;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */
@WebService(portName = "WSCustodiaImagenesSOAP", serviceName = "WSCustodiaImagenes", targetNamespace = "http://ArchivoDigital.ws.services.tributasenasturias.es/WSCustodiaImagenes/", wsdlLocation = "/wsdls/WSCustodiaImagenes.wsdl", endpointInterface = "es.tributasenasturias.services.ws.custodiaimagenes.WSCustodiaImagenes")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain(file="HandlerChain.xml")
public class WSCustodiaImagenes_WSCustodiaImagenesSOAPImpl implements
		WSCustodiaImagenes {

	public WSCustodiaImagenes_WSCustodiaImagenesSOAPImpl() {
	}
	
	@Resource
	WebServiceContext context;
	/**
	 * 
	 * @param nombreArchivo
	 * @param limite
	 * @param archivoRes
	 * @param archivo
	 * @param nomArchivo
	 * @param codUsuario
	 * @param descError
	 * @param codError
	 */
	public void custodiaFicAcuseRecibo(String nombreArchivo, byte[] archivo,
			String codUsuario, int limite, Holder<byte[]> archivoRes,
			Holder<String> codError, Holder<String> descError,
			Holder<String> nomArchivo) {

		Logger logger= null;
		try {
			String idLlamada= (String) context.getMessageContext().get(Constantes.ID_LLAMADA);
			Preferencias	 pref= (Preferencias) context.getMessageContext().get(Constantes.PREFERENCIAS);
			if (pref==null) {
				throw new Exception ("No se han encontrado las preferencias en el contexto de la llamada");
			}
			logger= new Logger(idLlamada, pref.getAppLogDir(), pref.getAppLogFile());
			
			logger.info("Petición custodia fichero multas");
			logger.info("codigoUsuario:" + codUsuario);
			logger.info("limite:" + limite);
			
			Datos datos = new Datos();
			datos.CustodiaFicMultas(nombreArchivo, archivo, codUsuario, limite, archivoRes, codError, descError, nomArchivo);
			
			if(descError.value!="" && descError.value!=null)
				logger.error("ERROR:" + descError.value);
			
		} catch (Exception ex){
			if (logger!=null) {
				logger.error("Error en la ejecución del servicio web custodiaFicAcuseRecibo: " + ex.getMessage());
			} else 
			{
				System.err.println("WSCustodiaImagenes: Error en la ejecución del servicio custodiaFicAcuseRecibo: "+ ex.getMessage());
				ex.printStackTrace(System.err);
			}
			throw new WebServiceException(ex);
		}
		return;
	}

}
