
package es.gob.administracionelectronica.notifica.ws.notificaws_v2;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NotificaWsV2Service", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/", wsdlLocation = "META-INF/wsdl/GestionEnvios_V21.wsdl")
public class NotificaWsV2Service
    extends Service
{

    private final static URL NOTIFICAWSV2SERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTIFICAWSV2SERVICE_EXCEPTION;
    private final static QName NOTIFICAWSV2SERVICE_QNAME = new QName("https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/", "NotificaWsV2Service");

    static {
    	//Modificado, para que en lugar de en META-INF, lo recupere directamente de un directorio bajo este paquete
        NOTIFICAWSV2SERVICE_WSDL_LOCATION = NotificaWsV2Service.class.getClassLoader().getResource("/es/gob/administracionelectronica/notifica/ws/notificaws_v2/wsdl/GestionEnvios_V21.wsdl");
        WebServiceException e = null;
        if (NOTIFICAWSV2SERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'wsdl/GestionEnvios_V21.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        NOTIFICAWSV2SERVICE_EXCEPTION = e;
    }

    public NotificaWsV2Service() {
        super(__getWsdlLocation(), NOTIFICAWSV2SERVICE_QNAME);
    }

    public NotificaWsV2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns NotificaWsV2PortType
     */
    @WebEndpoint(name = "NotificaWsV2Port")
    public NotificaWsV2PortType getNotificaWsV2Port() {
        return super.getPort(new QName("https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/", "NotificaWsV2Port"), NotificaWsV2PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificaWsV2PortType
     */
    @WebEndpoint(name = "NotificaWsV2Port")
    public NotificaWsV2PortType getNotificaWsV2Port(WebServiceFeature... features) {
        return super.getPort(new QName("https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/", "NotificaWsV2Port"), NotificaWsV2PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICAWSV2SERVICE_EXCEPTION!= null) {
            throw NOTIFICAWSV2SERVICE_EXCEPTION;
        }
        return NOTIFICAWSV2SERVICE_WSDL_LOCATION;
    }

}
