package es.gob.administracionelectronica.notifica.ws.notificaws_v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-02-26T12:04:24.395+01:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/", name = "NotificaWsV2PortType")
@XmlSeeAlso({https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.getcies.ObjectFactory.class, https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.ObjectFactory.class, https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.altaremesaenvios.ObjectFactory.class})
public interface NotificaWsV2PortType {

    @WebMethod(action = "infoEnvioV2")
    @RequestWrapper(localName = "infoEnvioV2", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2", className = "https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.InfoEnvioV2")
    @ResponseWrapper(localName = "resultadoInfoEnvioV2", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2", className = "https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.ResultadoInfoEnvioV2")
    public void infoEnvioV2(
        @WebParam(mode = WebParam.Mode.INOUT, name = "identificador", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<java.lang.String> identificador,
        @WebParam(name = "apiKey", targetNamespace = "", header = true)
        java.lang.String apiKey,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<java.lang.String> estado,
        @WebParam(mode = WebParam.Mode.OUT, name = "concepto", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<java.lang.String> concepto,
        @WebParam(mode = WebParam.Mode.OUT, name = "descripcion", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<java.lang.String> descripcion,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigoOrganismoEmisor", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.CodigoDIR> codigoOrganismoEmisor,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigoOrganismoEmisorRaiz", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.CodigoDIR> codigoOrganismoEmisorRaiz,
        @WebParam(mode = WebParam.Mode.OUT, name = "tipoEnvio", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<java.lang.String> tipoEnvio,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaCreacion", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaCreacion,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaPuestaDisposicion", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaPuestaDisposicion,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaCaducidad", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaCaducidad,
        @WebParam(mode = WebParam.Mode.OUT, name = "retardo", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<java.math.BigInteger> retardo,
        @WebParam(mode = WebParam.Mode.OUT, name = "procedimiento", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.Procedimiento> procedimiento,
        @WebParam(mode = WebParam.Mode.OUT, name = "documento", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.Documento> documento,
        @WebParam(mode = WebParam.Mode.OUT, name = "referenciaEmisor", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<java.lang.String> referenciaEmisor,
        @WebParam(mode = WebParam.Mode.OUT, name = "titular", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.Persona> titular,
        @WebParam(mode = WebParam.Mode.OUT, name = "destinatarios", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.Destinatarios> destinatarios,
        @WebParam(mode = WebParam.Mode.OUT, name = "entregaPostal", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.EntregaPostal> entregaPostal,
        @WebParam(mode = WebParam.Mode.OUT, name = "entregaDEH", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.EntregaDEH> entregaDEH,
        @WebParam(mode = WebParam.Mode.OUT, name = "datados", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.Datados> datados,
        @WebParam(mode = WebParam.Mode.OUT, name = "certificacion", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.Certificacion> certificacion,
        @WebParam(mode = WebParam.Mode.OUT, name = "opcionesEnvio", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/infoEnvioV2")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.infoenviov2.Opciones> opcionesEnvio
    );

    @WebMethod(action = "getCies")
    @RequestWrapper(localName = "getCies", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/getCies", className = "https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.getcies.GetCies")
    @ResponseWrapper(localName = "resultadoGetCies", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/getCies", className = "https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.getcies.ResultadoGetCies")
    public void getCies(
        @WebParam(name = "organismoEmisor", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/getCies")
        java.lang.String organismoEmisor,
        @WebParam(name = "apiKey", targetNamespace = "", header = true)
        java.lang.String apiKey,
        @WebParam(mode = WebParam.Mode.OUT, name = "cies", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/getCies")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.getcies.Cies> cies,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigoRespuesta", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/getCies")
        javax.xml.ws.Holder<java.lang.String> codigoRespuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "descripcionRespuesta", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/getCies")
        javax.xml.ws.Holder<java.lang.String> descripcionRespuesta
    );

    @WebMethod(action = "altaRemesaEnvios")
    @RequestWrapper(localName = "altaRemesaEnvios", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios", className = "https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.altaremesaenvios.AltaRemesaEnvios")
    @ResponseWrapper(localName = "resultadoAltaRemesaEnvios", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios", className = "https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.altaremesaenvios.ResultadoAltaRemesaEnvios")
    public void altaRemesaEnvios(
        @WebParam(mode = WebParam.Mode.INOUT, name = "codigoOrganismoEmisor", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        javax.xml.ws.Holder<java.lang.String> codigoOrganismoEmisor,
        @WebParam(name = "tipoEnvio", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        java.math.BigInteger tipoEnvio,
        @WebParam(name = "concepto", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        java.lang.String concepto,
        @WebParam(name = "descripcion", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        java.lang.String descripcion,
        @WebParam(name = "fechaEnvioProgramado", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        javax.xml.datatype.XMLGregorianCalendar fechaEnvioProgramado,
        @WebParam(name = "procedimiento", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        java.lang.String procedimiento,
        @WebParam(name = "documento", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.altaremesaenvios.Documento documento,
        @WebParam(name = "envios", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.altaremesaenvios.Envios envios,
        @WebParam(name = "opcionesRemesa", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.altaremesaenvios.Opciones opcionesRemesa,
        @WebParam(name = "apiKey", targetNamespace = "", header = true)
        java.lang.String apiKey,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigoRespuesta", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        javax.xml.ws.Holder<java.lang.String> codigoRespuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "descripcionRespuesta", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        javax.xml.ws.Holder<java.lang.String> descripcionRespuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaCreacion", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaCreacion,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultadoEnvios", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/notificaws_v2/1.0/altaRemesaEnvios")
        javax.xml.ws.Holder<https.administracionelectronica_gob_es.notifica.ws.notificaws_v2._1_0.altaremesaenvios.ResultadoEnvios> resultadoEnvios
    );
}
