package es.tributasenasturias.servicios.asturcon.pagosEnte;

import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.annotation.Resource;
import javax.xml.ws.WebServiceContext;

import es.tributasenasturias.servicios.asturcon.pagosEnte.Utils.Constantes;
import es.tributasenasturias.servicios.asturcon.pagosEnte.Utils.Utils;
import es.tributasenasturias.servicios.asturcon.pagosEnte.context.CallContext;
import es.tributasenasturias.servicios.asturcon.pagosEnte.context.CallContextConstants;
import es.tributasenasturias.servicios.asturcon.pagosEnte.context.CallContextManager;
import es.tributasenasturias.servicios.asturcon.pagosEnte.preferencias.Preferencias;
import es.tributasenasturias.servicios.asturcon.pagosEnte.preferencias.PreferenciasException;
import es.tributasenasturias.servicios.asturcon.pagosEnte.preferencias.PreferenciasFactory;
import es.tributasenasturias.utils.log.LogFactory;
import es.tributasenasturias.utils.log.Logger;

/*
 * SEI del servicio de presentación de pagos y anulaciones de traba que está disponible para Asturcon.
 * Permitirá indicar al sistema TRibutas los pagos y anulaciones de trabas generados a partir de una consulta de deuda previa.
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */
@WebService(portName = "PagoDeudasSOAP", serviceName = "PagoDeudasEPST", targetNamespace = "http://servicios.tributasenasturias.es/Asturcon/PagoDeudasEPST/", wsdlLocation = "/wsdls/AsturconPagosEnte.wsdl", endpointInterface = "es.tributasenasturias.servicios.asturcon.pagosEnte.PagoDeudasEPST")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain(file="HandlerChain.xml")
public class PagoDeudasEPST_PagoDeudasSOAPImpl implements PagoDeudasEPST {

	@Resource WebServiceContext wContext;
	public PagoDeudasEPST_PagoDeudasSOAPImpl() {
		//La primera vez que se carga en memoria la clase, debería crear el fichero de preferencias.
		//Esto es al desplegar la aplicación, si no ha podido crearla ya más adelante lo intentará 
		//al usar las funciones. 
		try
		{
			PreferenciasFactory.newInstance();
		}
		catch (Exception ex)
		{}
	}

	/**
	 * Operación de recepción de pagos y anulaciones. Permite que el sistema Asturcon XXI envíe los pagos realizados y 
	 * qué anulaciones de traba deben llevarse a cabo en el sistema Tributas. 
	 * @param mensaje Mensaje que contiene los datos de pagos realizados y anulaciones de traba.
	 * @return returns
	 *         es.tributasenasturias.servicios.asturcon.pagosEnte.MENSAJEOut
	 */
	public MENSAJEOut enviarPagos(MENSAJEIn mensaje) {
		Logger log=null;
		try
		{
			//Creamos un contexto de llamada, para pasar parámetros como preferencias a las clases
			//que dependan de esta
			CallContext context = CallContextManager.newCallContext();
			Preferencias pref = (Preferencias) wContext.getMessageContext().get(Constantes.VAR_PREFERENCIAS);
			if (pref==null) //No debería, a menos que se haya eliminado el manejador que lo crea.
			{
				pref=PreferenciasFactory.newInstance();
			}
			String idSesion=(String)wContext.getMessageContext().get(Constantes.VAR_ID_SESION);
			if (idSesion==null || idSesion.equals(""))
			{
				//Recuperamos en este momento el identificador único.
				idSesion=Utils.getIdLlamada();
				wContext.getMessageContext().put(Constantes.VAR_ID_SESION, idSesion);
			}
			String xml=(String)wContext.getMessageContext().get(Constantes.VAR_XMLSOURCE);
			
			log = (Logger) wContext.getMessageContext().get(Constantes.VAR_LOG_APLICACION);
			if (log==null)
			{
				log=LogFactory.newLogger(pref.getModoLog(), pref.getFicheroLogApp(), idSesion);
			}
			log.debug(xml);
			context.setItem(CallContextConstants.LOG_APLICACION, log);
			context.setItem(CallContextConstants.ID_SESION, idSesion);
			context.setItem(CallContextConstants.PREFERENCIAS, pref);
			context.setItem(CallContextConstants.TEXTO_XML, xml);
			//ConsultaDeudaWorker con = new ConsultaDeudaWorker(context);
			PagoEnteWorker pg = new PagoEnteWorker(context);
			return pg.enviarPagos(mensaje);
		}
		catch (PreferenciasException ex)
		{
			if (log!=null)
			{
				log.error("Error inesperado en la llamada al servicio Web:" + ex.getMessage(), ex);
			}
		}
		return null;
	}

}
