
package es.tributasenasturias.lanzador.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "lanzaPLService", targetNamespace = "http://stpa/services", wsdlLocation = "http://bus.desa.epst.pa:7101/WSInternos/ProxyServices/PXLanzador?wsdl")
public class LanzaPLService
    extends Service
{

    private final static URL LANZAPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.tributasenasturias.lanzador.impl.LanzaPLService.class.getName());
    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.tributasenasturias.lanzador.impl.LanzaPLService.class.getResource(".");
            url = new URL(baseUrl, "wsdl/PXLanzador.wsdl");
        	if (url == null) {
        		url = new URL("http://bus:7101/WSInternos/ProxyServices/PXLanzador?wsdl");
        	}
        } catch (MalformedURLException e) {
        	logger.warning("Failed to create URL for the wsdl Location: 'wsdl/PXLanzador.wsdl'");
            logger.warning(e.getMessage());
        }
        LANZAPLSERVICE_WSDL_LOCATION = url;
    }

    public LanzaPLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LanzaPLService() {
        super(LANZAPLSERVICE_WSDL_LOCATION, new QName("http://stpa/services", "lanzaPLService"));
    }

    /**
     * 
     * @return
     *     returns LanzaPL
     */
    @WebEndpoint(name = "lanzaPLSoapPort")
    public LanzaPL getLanzaPLSoapPort() {
        return (LanzaPL)super.getPort(new QName("http://stpa/services", "lanzaPLSoapPort"), LanzaPL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LanzaPL
     */
    @WebEndpoint(name = "lanzaPLSoapPort")
    public LanzaPL getLanzaPLSoapPort(WebServiceFeature... features) {
        return (LanzaPL)super.getPort(new QName("http://stpa/services", "lanzaPLSoapPort"), LanzaPL.class, features);
    }

}
