
package es.tributasenasturias.seguridad.autenticacion;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AutenticacionEPST", targetNamespace = "http://servicios.tributasenasturias.es/AutenticacionEPST/", wsdlLocation = "http://bus.desa.epst.pa:7101/WSAutenticacionEPST/ProxyServices/PXAutenticacionEPST?wsdl")
public class AutenticacionEPST_Service
    extends Service
{

    private final static URL AUTENTICACIONEPST_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.tributasenasturias.seguridad.autenticacion.AutenticacionEPST_Service.class.getName());
    static {
        URL url = null;
        try {
        	URL baseUrl;
            baseUrl = es.tributasenasturias.seguridad.autenticacion.AutenticacionEPST_Service.class.getResource(".");
            url = new URL(baseUrl, "wsdl/PXAutenticacionEPST.wsdl");
        	if (url == null) {
        		url = new URL("http://bus:7101/WSAutenticacionEPST/ProxyServices/PXAutenticacionEPST?wsdl");
        	}
        } catch (MalformedURLException e) {
        	logger.warning("Failed to create URL for the wsdl Location: 'wsdl/PXFirmaDigital.wsdl'");
            logger.warning(e.getMessage());
        }
        AUTENTICACIONEPST_WSDL_LOCATION = url;
    }

    public AutenticacionEPST_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutenticacionEPST_Service() {
        super(AUTENTICACIONEPST_WSDL_LOCATION, new QName("http://servicios.tributasenasturias.es/AutenticacionEPST/", "AutenticacionEPST"));
    }

    /**
     * 
     * @return
     *     returns AutenticacionEPST
     */
    @WebEndpoint(name = "AutenticacionEPSTSOAP")
    public AutenticacionEPST getAutenticacionEPSTSOAP() {
        return (AutenticacionEPST)super.getPort(new QName("http://servicios.tributasenasturias.es/AutenticacionEPST/", "AutenticacionEPSTSOAP"), AutenticacionEPST.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutenticacionEPST
     */
    @WebEndpoint(name = "AutenticacionEPSTSOAP")
    public AutenticacionEPST getAutenticacionEPSTSOAP(WebServiceFeature... features) {
        return (AutenticacionEPST)super.getPort(new QName("http://servicios.tributasenasturias.es/AutenticacionEPST/", "AutenticacionEPSTSOAP"), AutenticacionEPST.class, features);
    }

}
