
package es.tributasenasturias.seguridad.autenticacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AutenticacionEPST", targetNamespace = "http://servicios.tributasenasturias.es/AutenticacionEPST/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutenticacionEPST {


    /**
     * 
     * @param nombre
     * @param apellido2
     * @param cif
     * @param razonSocial
     * @param tipo
     * @param apellido1
     * @param nifNIE
     * @param idError
     * @param esError
     * @param certificado
     * @param mensajeError
     */
    @WebMethod(action = "http://servicios.tributasenasturias.es/AutenticacionEPST/login")
    @RequestWrapper(localName = "login", targetNamespace = "http://servicios.tributasenasturias.es/AutenticacionEPST/", className = "es.tributasenasturias.autenticacionepst.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://servicios.tributasenasturias.es/AutenticacionEPST/", className = "es.tributasenasturias.autenticacionepst.LoginResponse")
    public void login(
        @WebParam(name = "certificado", targetNamespace = "")
        String certificado,
        @WebParam(name = "esError", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Boolean> esError,
        @WebParam(name = "idError", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> idError,
        @WebParam(name = "mensajeError", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> mensajeError,
        @WebParam(name = "CIF", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> cif,
        @WebParam(name = "NIF_NIE", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> nifNIE,
        @WebParam(name = "razon_social", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> razonSocial,
        @WebParam(name = "apellido1", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> apellido1,
        @WebParam(name = "apellido2", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> apellido2,
        @WebParam(name = "nombre", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> nombre,
        @WebParam(name = "tipo", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> tipo);

}
