package es.tributasenasturias.services.ws.wsepi;

import javax.annotation.Resource;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.Holder;
import javax.jws.HandlerChain;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.WebServiceException;

import es.tributasenasturias.services.ws.wsepi.bd.Documentos;
import es.tributasenasturias.services.ws.wsepi.utils.log.Logger;
import es.tributasenasturias.services.ws.wsepi.utils.log.Preferencias.Preferencias;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */
@WebService(portName = "EPISOAP", serviceName = "EPI", targetNamespace = "http://WSEPI.ws.services.tributasenasturias.es/EPI/", wsdlLocation = "/wsdls/EPI.wsdl", endpointInterface = "es.tributasenasturias.services.ws.wsepi.EPI")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain(file="HandlerChain.xml")
public class EPI_EPISOAPImpl implements EPI {

	public EPI_EPISOAPImpl() {
	}

	@Resource
	WebServiceContext context;
	/**
	 * 
	 * @param ideepi
	 * @param idgdre
	 * @param idadar
	 * @param error
	 * @param idArchivo
	 * @param datosArchivo
	 */
	public void ejecutarCallback(int idadar, int ideepi, int idgdre,
			Holder<Integer> idArchivo, Holder<String> datosArchivo,
			Holder<String> error) {
		Logger logger=null;
		try{
			String idLlamada= (String) context.getMessageContext().get(Constantes.ID_LLAMADA);
			Preferencias pref= (Preferencias) context.getMessageContext().get(Constantes.PREFERENCIAS);
			if (pref==null) {
				throw new Exception ("No se han encontrado las preferencias en el contexto de la llamada");
			}
			logger= new Logger(idLlamada, pref.getAppLogDir(), pref.getAppLogFile());
			logger.trace("INICIO LLAMADA METODO WEB ejecutarCallback");

			Documentos consulta = new Documentos(pref, logger, idLlamada);
			consulta.EjecutarCallback(idadar, ideepi, idgdre, idArchivo, datosArchivo, error);
			
			logger.trace("FIN LLAMADA METODO WEB ejecutarCallback");
		}catch (Exception ex){
			if (logger!=null) {
				logger.error("Error en la ejecución del servicio web ejecutarCallback: " + ex.getMessage());
			} else  {
				System.err.println ("WSEPI: Error en servicio web ejecutarCallback:" + ex.getMessage());
				ex.printStackTrace(System.err);
			}
			throw new WebServiceException(ex);
		}
        return;
	}

	/**
	 * 
	 * @param error
	 * @param hash
	 * @param archivo
	 * @param identificador
	 * @param nombreFichero
	 * @param idArchivo
	 * @param tipoElemento
	 * @param firma
	 * @param datosArchivo
	 * @param codigoUsuario
	 */
	public void cuastodiaArchivo(String codigoUsuario, String identificador,
			String tipoElemento, String nombreFichero, byte[] archivo,
			String hash, FirmaType firma, Holder<Integer> idArchivo,
			Holder<String> datosArchivo, Holder<String> error) {
		Logger logger= null;
		try{
			String idLlamada= (String) context.getMessageContext().get(Constantes.ID_LLAMADA);
			Preferencias pref= (Preferencias) context.getMessageContext().get(Constantes.PREFERENCIAS);
			if (pref==null) {
				throw new Exception ("No se han encontrado las preferencias en el contexto de la llamada");
			}
			logger= new Logger( idLlamada, pref.getAppLogDir(), pref.getAppLogFile());
			logger.trace("INICIO LLAMADA METODO WEB custodiaArchivo");
	
			Documentos consulta = new Documentos(pref, logger, idLlamada);
			consulta.CustodiaArchivo(codigoUsuario, nombreFichero, tipoElemento, archivo, identificador, hash,
					// CRUBENCVS 43599 25/10/2021. Ahora, los parámetros de firma se pasan en su propio nodo,
					// con una estructura similar a la de Archivo digital
					/* INIPETITRIBUTAS-30 ENAVARRO ** 21/04/2021 ** Buzon de notificaciones */
		    		//custodiarCsv, 
		    		/* FINPETITRIBUTAS-30 ENAVARRO ** 21/04/2021 ** Buzon de notificaciones */
					firma,
					// FIN CRUBENCVS
					idArchivo ,datosArchivo, error);
			
			logger.trace("FIN LLAMADA METODO WEB custodiaArchivo");
		}catch (Exception ex){
			if (logger!=null) {
				logger.error("Error en la ejecución del servicio web custodiaArchivo: " + ex.getMessage());
			} else  {
				System.err.println ("WSEPI: Error en servicio web custodiaArchivo:" + ex.getMessage());
				ex.printStackTrace(System.err);
			}
		}
        return;
	}
}
